---

- name: Check if okta auth is already enabled
  uri:
    url: "{{ vault_api_addr }}/v1/sys/auth"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    method: GET
    status_code: 200
  no_log: true
  register: auth_methods

- name: Enable okta auth
  uri:
    url: "{{ vault_api_addr }}/v1/sys/auth/okta"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    method: POST
    body_format: json
    body:
      type: okta
    status_code: 204
  no_log: true
  when: not ansible_check_mode and not (auth_methods.json | json_query('"okta/"'))

- name: Setup okta authentication
  uri:
    url: "{{ vault_api_addr }}/v1/auth/okta/config"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    method: POST
    body_format: json
    body: "{{ vault_auth_okta_config }}"
    status_code: 204
  no_log: true
  when: not ansible_check_mode and not (auth_methods.json | json_query('"okta/"'))
