---

- name: Check if LDAP auth is already enabled
  uri:
    url: "{{ vault_api_addr }}/v1/sys/auth"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    method: GET
    status_code: 200
  no_log: true
  register: auth_methods

- name: Enable LDAP auth
  uri:
    url: "{{ vault_api_addr }}/v1/sys/auth/ldap"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    method: POST
    body_format: json
    body:
      type: ldap
      config: "{{ vault_auth_ldap_method_config }}"
    status_code: 204
  no_log: true
  when: not ansible_check_mode and not (auth_methods.json | json_query('"ldap/"'))

- name: Setup LDAP authentication
  uri:
    url: "{{ vault_api_addr }}/v1/auth/ldap/config"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    method: POST
    body_format: json
    body: "{{ vault_auth_ldap_config }}"
    status_code: 204
  no_log: true
  when: not ansible_check_mode and not (auth_methods.json | json_query('"ldap/"'))
