---

- include_tasks: install.yml
- include_tasks: configure.yml
- include_tasks: init.yml
  when: vault_autounseal_aws
- include_tasks: login.yml

- include_tasks: auth_ldap.yml
  when: vault_auth_ldap_enable
- include_tasks: auth_aws.yml
  when: vault_auth_aws_enable
- include_tasks: auth_userpass.yml
  when: vault_auth_userpass_enable
- include_tasks: okta.yml
  when: vault_auth_okta_enable
