---

- name: restart vault
  service:
    state: restarted
    name: vault
  when: vault_service_state == "started"

- name: start vault
  service:
    state: started
    name: vault
  when: vault_service_state == "started"
